name: NodeJS with Webpack

on:
  push:
    branches: [ "master", "main", "test-deployment" ]
env: 
 # token: ${{ secrets.TOKEN }}
 token: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn install

    - name: Deploy
      run: |
        git remote set-url origin https://yicccccc:$token@github.com/yicccccc/yi-test
        git config --global user.email "yi_chiang@outlook.com"
        git config --global user.name "Yi"
        yarn run deploy
